export type AttrVars = {
  x?: number | string;
  y?: number | string;
  cx?: number | string;
  cy?: number | string;
  r?: number | string;
  rx?: number | string;
  ry?: number | string;
  x1?: number | string;
  y1?: number | string;
  x2?: number | string;
  y2?: number | string;
  width?: number | string;
  height?: number | string;
  fill?: string;
  stroke?: string;
  opacity?: number | string;
  fillOpacity?: number | string;
  strokeOpacity?: number | string;
  strokeWidth?: number | string;
  strokeDashoffset?: number | string;
  strokeDasharray?: string;
  points?: string;
  d?: string;
  viewBox?: string;
  stdDeviation?: number | string;
  offset?: number | string;
  [key: string]: number | string | undefined;
};
